window.TEST_REGEXP = /sane-tests\/editor\/tokyo\/.*Spec\.js$/i;
window.allTestFiles = [
	"editor/tokyo/ideplatform/plugin/baseValidator/service/annotationsHelperIntegrationSpec",
	"editor/tokyo/ideplatform/plugin/baseValidator/unit/unitRulesSecuritySpec",
	"editor/tokyo/ideplatform/plugin/baseValidator/unit/annotationsHelperSpec",
	"editor/tokyo/ideplatform/plugin/baseValidator/unit/validatorUserSettingsSpec",
	"editor/tokyo/ideplatform/plugin/baseValidator/service/concreteBasevalidatorSpec",
	"editor/tokyo/ideplatform/plugin/baseValidator/service/BaseValidatorListSpec",
	"editor/tokyo/ideplatform/plugin/baseValidator/service/baseValidatorToAnnotationsSpec",
	"editor/tokyo/ideplatform/plugin/baseValidator/service/validateMultipleSpec",
	"editor/tokyo/ideplatform/plugin/baseValidator/service/locatingValidatorSpec",
	"editor/tokyo/ideplatform/plugin/baseValidator/service/rulesManagerSpec",
	"editor/tokyo/ideplatform/plugin/baseValidator/service/rulesManagerCacheSpec",
	"editor/tokyo/saptoolsets/fiori/editor/plugin/fiorijsvalidator/unit/configReaderSpec",
	"editor/tokyo/saptoolsets/fiori/editor/plugin/fiorijsvalidator/unit/jsValidatorHelperSpec",
	"editor/tokyo/saptoolsets/fiori/editor/plugin/fiorijsvalidator/unit/jsValidatorSpec",
	"editor/tokyo/saptoolsets/fiori/editor/plugin/fiorijsvalidator/unit/displayFormatSpec",
	"editor/tokyo/saptoolsets/fiori/problemsView/service/validationTriggersSpec",
	"editor/tokyo/saptoolsets/fiori/problemsView/service/PVcodeValidationSpec",
	"editor/tokyo/saptoolsets/fiori/problemsView/unit/cacheManagerSpec",
	"editor/tokyo/saptoolsets/fiori/problemsView/unit/validationStoreManagerSpec",
	"editor/tokyo/saptoolsets/fiori/problemsView/unit/queueManagerSpec",
	"editor/tokyo/saptoolsets/fiori/problemsView/unit/problemViewControllerSpec",
	"editor/tokyo/toolsets/plugin/javascript/unit/jsdocgenImplSpec",
	"editor/tokyo/toolsets/plugin/javascript/unit/jsdocgencommandSpec",
	"editor/tokyo/saptoolsets/fiori/problemsView/service/baseValidatorAdopterSpec",
	"editor/tokyo/toolsets/plugin/json/unit/jsonParseSpec",
	"editor/tokyo/toolsets/plugin/json/unit/isMyJsonValidAdopterSpec",
	"editor/tokyo/beautify/BeautifierProcessorSpec",
	"editor/tokyo/beautify/BeautifyCommandSpec",
	"editor/tokyo/toolsets/plugin/javascript/unit/jsOutlineSpec",
	"editor/tokyo/toolsets/plugin/javascript/service/jsValidatorSpec",
	"editor/tokyo/toolsets/plugin/javascript/service/jsValidatorDisplaySpec",
	"editor/tokyo/toolsets/plugin/json/service/neoAppValidatorSpec",
	"editor/tokyo/toolsets/plugin/json/service/jsonValidatorSpec",
	"editor/tokyo/toolsets/plugin/json/service/jsonValidatorPortableSpec",
	"editor/tokyo/toolsets/plugin/javascript/service/beautifierSpec",
	"editor/tokyo/saptoolsets/fiori/editor/fiorixmlanalysis/fiorixmlAnalysisSpec",
	"editor/tokyo/toolsets/plugin/xml/service/xmlBeautifierImplSpec",
	"editor/tokyo/toolsets/plugin/xml/service/xmlBeautifierIntegrationSpec",
	"editor/tokyo/toolsets/plugin/xml/service/xmlFormatterIntegrationSpec",
	"editor/tokyo/toolsets/plugin/xml/unit/xmlFormatterSpec",
	"editor/tokyo/toolsets/plugin/xml/service/xmlValidatorSpec"
];

window.customPaths = {
	"editor": window.webappPath() + "test-resources/sap/watt/sane-tests/editor",
	"sinon": window.webappPath() + "test-resources/sap/watt/sane-tests/libs/sinon-1.17.2",
	"jquery": window.webappPath() + "resources/sap/watt/lib/jquery/jquery-1.10.2"
};