define([
        "hanaddl/backendaccess/MetadataServices",
        "hanaddl/BaseCdsDdlParser",
        "hanaddl/CdsDdlPadFileResolver",
        "hanaddl/CodeResolver",
        "hanaddl/CompareUtil",
        "hanaddl/CompilationUnitManager",
        "hanaddl/CompilationUnitUtil",
        "hanaddl/ContextUtil",
        "hanaddl/DdlErrorRecoveryHook",
        "hanaddl/DdlParserFactoryRespectingBackendVersion",
        "hanaddl/DdlSourceUtil",
        "hanaddl/HanaAnnotationUtil",
        "hanaddl/HanaDdlCodeCompletion",
        "hanaddl/IBaseCdsDdlParserConstants",
        "hanaddl/IdNextKeywordCompletion",
        "hanaddl/Messages",
        "hanaddl/NamespaceUtil",
        "hanaddl/PrimitiveTypeUtil",
        "hanaddl/StmtUtil",
        "hanaddl/UsingDirectiveInserter",
        "hanaddl/VersionsFactory",
        "hanaddl/DdlParserFactoryApi"
    ], //dependencies
    function (MetadataServices,
              BaseCdsDdlParser,
              CdsDdlPadFileResolver,
              CodeResolver,
              CompareUtil,
              CompilationUnitManager,
              CompilationUnitUtil,
              ContextUtil,
              DdlErrorRecoveryHook,
              DdlParserFactoryRespectingBackendVersion,
              DdlSourceUtil,
              HanaAnnotationUtil,
              HanaDdlCodeCompletion,
              IBaseCdsDdlParserConstants,
              IdNextKeywordCompletion,
              Messages,
              NamespaceUtil,
              PrimitiveTypeUtil,
              StmtUtil,
              UsingDirectiveInserter,
              VersionsFactory,
              DdlParserFactoryApi) {
        return {
            MetadataServices: MetadataServices,
            BaseCdsDdlParser: BaseCdsDdlParser,
            CdsDdlPadFileResolver: CdsDdlPadFileResolver,
            CodeResolver: CodeResolver,
            CompareUtil: CompareUtil,
            CompilationUnitManager: CompilationUnitManager,
            CompilationUnitUtil: CompilationUnitUtil,
            ContextUtil: ContextUtil,
            DdlErrorRecoveryHook: DdlErrorRecoveryHook,
            DdlParserFactoryRespectingBackendVersion: DdlParserFactoryRespectingBackendVersion,
            DdlSourceUtil: DdlSourceUtil,
            HanaAnnotationUtil: HanaAnnotationUtil,
            HanaDdlCodeCompletion: HanaDdlCodeCompletion,
            IBaseCdsDdlParserConstants: IBaseCdsDdlParserConstants,
            IdNextKeywordCompletion: IdNextKeywordCompletion,
            Messages: Messages,
            NamespaceUtil: NamespaceUtil,
            PrimitiveTypeUtil: PrimitiveTypeUtil,
            StmtUtil: StmtUtil,
            UsingDirectiveInserter: UsingDirectiveInserter,
            VersionsFactory: VersionsFactory,
            DdlParserFactoryApi: DdlParserFactoryApi
        };
    }
);
