define(["w5g/w5gTestUtils" , "sap/watt/saptoolsets/fiori/editor/plugin/ui5wysiwygeditor/utils/EventsUtils"],
		function (w5gTestUtils , EventsUtils) {
			"use strict";


			var
					oFakeContext = {
						service: {
							document : {},
							content : {}
						}
					},
					sController =
							'function global1(){' +
							'}' +
							'function global2(){' +
							'}' +
							'sap.ui.core.mvc.Controller.extend("xmlView.Events",{' +
								'action1 : function(){' +
								'	function inner(){' +
								'	}' +
							'	}' +
							'	,' +
								'action2 : function(){' +
								'}' +
							'});';


			describe("W5G Events Utils" , function () {

				before(function () {
					EventsUtils.init(oFakeContext);
				});

				it("test fetch public methods from controller" , function () {
					var sMethods = EventsUtils.fetchMethodsFromController(sController);
					assert.equal(sMethods.length , 2 , "expecting two public methods for this controller");
					var sMethodNames = _.map(sMethods , 'signature');
					expect(sMethodNames).to.include('action1');
					expect(sMethodNames).to.include('action2');
				});

				it("test fetch method range from controller" , function () {
					var aRange = EventsUtils.fetchMethodRangeFromController(sController , 'action1');
					expect(aRange).to.exist;
					assert.equal(aRange.length , 2 , "range should be array of two numbers");
					assert.equal(aRange[0] , 92 , "start index should be 92");
					assert.equal(aRange[1] , 135 , "end index should be 92");
				});

				it("test inject method to controller's code" , function () {

					var sExpectedFunction = "/**" +
							"*@memberOf xmlView.Events" +
							"*/" +
							"action3: function () {" +
							"	//This code was generated by the layout editor." +
							"}";

					var sNewController = EventsUtils.injectEventToController(sController , 'action3' , 'xmlView.Events');
					expect(sNewController.replace(/(\n|\t|\r)/g , "")).to.have.entriesCount(sExpectedFunction.replace(/(\n|\t|\r)/g , "") , 1);

				});


			});
		});


