define([
    "idetests/editor/plugin/analytics/tests/ModelBaseDocu",
    "idetests/editor/plugin/analytics/tests/ModelBaseTest",
    "idetests/editor/plugin/analytics/tests/ViewModelTest",
    "idetests/editor/plugin/analytics/tests/XmlReaderTest",
    "idetests/editor/plugin/analytics/tests/XmlWriterTest",
    "idetests/editor/plugin/analytics/tests/TypedObjectParserTest",
    "idetests/editor/plugin/analytics/tests/DiagramTest",
    "idetests/editor/plugin/analytics/tests/MetadataServicesTest",
    "idetests/editor/plugin/analytics/tests/ControlTest",
    "idetests/editor/plugin/analytics/tests/RepositoryXmlParserTest"
]);