define(
    [
        "commonddl/astmodel/AbapMethodImpl",
        "commonddl/astmodel/AbstractAnnotationImpl",
        "commonddl/astmodel/AbstractAnnotationValueImpl",
        "commonddl/astmodel/AnnotatedImpl",
        "commonddl/astmodel/AnnotationArrayValueImpl",
        "commonddl/astmodel/AnnotationDeclarationImpl",
        "commonddl/astmodel/AnnotationNameValuePairImpl",
        "commonddl/astmodel/AnnotationPathValueImpl",
        "commonddl/astmodel/AnnotationRecordValueImpl",
        "commonddl/astmodel/AnnotationValueImpl",
        "commonddl/astmodel/AnonymousTypeDeclarationImpl",
        "commonddl/astmodel/AssociationDeclarationImpl",
        "commonddl/astmodel/AssociationContainerImpl",
        "commonddl/astmodel/AstFactoryImpl",
        "commonddl/astmodel/AttributeDeclarationImpl",
        "commonddl/astmodel/BetweenExpressionImpl",
        "commonddl/astmodel/BooleanExpressionImpl",
        "commonddl/astmodel/BooleanType",
        "commonddl/astmodel/ColumnImpl",
        "commonddl/astmodel/CompExpressionImpl",
        "commonddl/astmodel/CompilationUnitImpl",
        "commonddl/astmodel/ComponentDeclarationImpl",
        "commonddl/astmodel/ConcatenationExpressionImpl",
        "commonddl/astmodel/ConstDeclarationImpl",
        "commonddl/astmodel/ContextDeclarationImpl",
        "commonddl/astmodel/DataSourceAssociationImpl",
        "commonddl/astmodel/DataSourceImpl",
        "commonddl/astmodel/DdlStatementImpl",
        "commonddl/astmodel/ElementDeclarationImpl",
        "commonddl/astmodel/EntityDeclarationImpl",
        "commonddl/astmodel/EnumerationDeclarationImpl",
        "commonddl/astmodel/EnumerationValueImpl",
        "commonddl/astmodel/EObjectContainmentEList",
        "commonddl/astmodel/EObjectImpl",
        "commonddl/astmodel/ExpressionContainerImpl",
        "commonddl/astmodel/ExpressionImpl",
        "commonddl/astmodel/ForeignKeyImpl",
        "commonddl/astmodel/FuncExpressionImpl",
        "commonddl/astmodel/GroupByEntryImpl",
        "commonddl/astmodel/GroupByImpl",
        "commonddl/astmodel/IAstFactory",
        "commonddl/astmodel/ImplementedByImpl",
        "commonddl/astmodel/InExpressionImpl",
        "commonddl/astmodel/JoinDataSourceImpl",
        "commonddl/astmodel/JoinEnum",
        "commonddl/astmodel/LikeExpressionImpl",
        "commonddl/astmodel/LiteralExpressionImpl",
        "commonddl/astmodel/NamedDeclarationImpl",
        "commonddl/astmodel/NamespaceDeclarationImpl",
        "commonddl/astmodel/NotExpressionImpl",
        "commonddl/astmodel/NullExpressionImpl",
        "commonddl/astmodel/OrderByEntryImpl",
        "commonddl/astmodel/OrderByImpl",
        "commonddl/astmodel/PathDeclarationImpl",
        "commonddl/astmodel/PathEntryImpl",
        "commonddl/astmodel/PathExpressionImpl",
        "commonddl/astmodel/PreAnnotationImpl",
        "commonddl/astmodel/ReturnStructureImpl",
        "commonddl/astmodel/ReturnStructureListImpl",
        "commonddl/astmodel/ReturnStructureNameImpl",
        "commonddl/astmodel/SelectListEntryExtensionImpl",
        "commonddl/astmodel/SelectListEntryImpl",
        "commonddl/astmodel/SelectListEntryType",
        "commonddl/astmodel/SelectListImpl",
        "commonddl/astmodel/SourceRangeImpl",
        "commonddl/astmodel/StatementContainerImpl",
        "commonddl/astmodel/StdFuncExpressionImpl",
        "commonddl/astmodel/TableFunctionImpl",
        "commonddl/astmodel/TypeDeclarationImpl",
        "commonddl/astmodel/UsingDirectiveImpl",
        "commonddl/astmodel/ViewDefinitionImpl",
        "commonddl/astmodel/ViewExtendImpl",
        "commonddl/astmodel/ViewSelectImpl",
        "commonddl/astmodel/SearchedCaseExpressionImpl",
        "commonddl/astmodel/SimpleCaseExpressionImpl",
        "commonddl/astmodel/CaseWhenExpressionImpl",
        "commonddl/astmodel/ArithmeticExpressionImpl",
        "commonddl/astmodel/PostAnnotationImpl",
        "commonddl/AbstractDdlCodeCompletionProposal",
        "commonddl/AbstractDdlParser",
        "commonddl/AbstractDdlVisitor",
        "commonddl/AnnotationPayload",
        "commonddl/AnnotationUtil",
        "commonddl/DdlCodeCompletionType",
        "commonddl/DdlColumnSelectListEntry",
        "commonddl/DdlCompletionProposal",
        "commonddl/DdlCompletionScope",
        "commonddl/DdlDataSourceAssociationDefinition",
        "commonddl/DdlDataSourceInformation",
        "commonddl/DdlDataSourceParameter",
        "commonddl/DdlErrorneousParserBackendInfo",
        "commonddl/DdlKeywordCodeCompletionProposal",
        "commonddl/DdlParserBackendInfo",
        "commonddl/DdlParserFactoryBackendVersion",
        "commonddl/DdlRndParserApi",
        "commonddl/DdlScanner",
        "commonddl/DdlSourceColoringCacheHelper",
        "commonddl/DdlSourceFormattingStyle",
        "commonddl/DdlStatementMatchUtil",
        "commonddl/DdlTypeUsagePayload",
        "commonddl/PredefinedDataType",
        "commonddl/SapDdlConstants",
        "commonddl/SapViewFormatter",
        "commonddl/TokenUtil",
        "commonddl/WordFormattingEnum",
        "commonddl/astmodel/SelectImpl",
        "commonddl/astmodel/ViewSelectSetImpl",
        "commonddl/Region",
        "commonddl/astmodel/RuleDeclarationImpl",
        "commonddl/astmodel/AccessPolicyDeclarationImpl",
        "commonddl/astmodel/RoleDeclarationImpl",
        "commonddl/astmodel/AspectDeclarationImpl",
        "commonddl/renderer/SourceRenderer",
        "commonddl/astmodel/CardinalityRestrictionImpl",
        "commonddl/sourcemodification/RemoveSelectListEntryCommand",
        "commonddl/sourcemodification/RemoveParameterCommand",
        "commonddl/sourcemodification/RemoveAliasForSelectListEntryCommand",
        "commonddl/sourcemodification/RemoveAnnotationCommand",
        "commonddl/differ/AstMerger",
        "commonddl/sourcemodification/ReplaceSelectListEntryCommand",
        "commonddl/sourcemodification/AddAnnotationCommand",
        "commonddl/sourcemodification/ReplaceAnnotationCommand",
        "commonddl/sourcemodification/ReplaceSingleTokenLexemCommand",
        "commonddl/sourcemodification/AddToListCommand",
        "commonddl/sourcemodification/ReplaceParameterCommand",
        "commonddl/sourcemodification/MoveAstObjectInListCommand",
        "commonddl/sourcemodification/AddAliasForSelectListEntryCommand",
        "commonddl/sourcemodification/AddSelectListEntryCommand",
        "commonddl/sourcemodification/AddAnnotationForViewDefinitionCommand",
        "commonddl/sourcemodification/AddAnnotationForSelectListEntryCommand",
        "commonddl/sourcemodification/ModifyAnnotationForSelectListEntryCommand",
        "commonddl/sourcemodification/ModifyAnnotationForViewDefinitionCommand",
        "commonddl/sourcemodification/ModifyEndUserTextCommand",
        "commonddl/sourcemodification/AddParameterCommand",
        "commonddl/sourcemodification/MoveSelectListEntryCommand",
        "commonddl/sourcemodification/SourceModificationCommandFactory",
        "commonddl/sourcemodification/SetWhereClauseCommand",
        "commonddl/astmodel/ConstructorFuncExpressionImpl",
        "commonddl/astmodel/ExpressionsContainerExpressionImpl",
        "commonddl/astmodel/ExtractFunctionExpressionImpl",
        "commonddl/astmodel/TrimFunctionExpressionImpl",
        "commonddl/astmodel/AbstractPathEntryImpl",
        "commonddl/astmodel/NestedFlattenedSelectListPathEntryImpl",
        "commonddl/astmodel/NestedSelectListPathEntryImpl",
        "commonddl/astmodel/IncludedRoleImpl",
        "commonddl/AstNodeUtil",
        "commonddl/CodePattern"
    ],

    function (AbapMethodImpl,
              AbstractAnnotationImpl,
              AbstractAnnotationValueImpl,
              AnnotatedImpl,
              AnnotationArrayValueImpl,
              AnnotationDeclarationImpl,
              AnnotationNameValuePairImpl,
              AnnotationPathValueImpl,
              AnnotationRecordValueImpl,
              AnnotationValueImpl,
              AnonymousTypeDeclarationImpl,
              AssociationDeclarationImpl,
              AssociationContainerImpl,
              AstFactoryImpl,
              AttributeDeclarationImpl,
              BetweenExpressionImpl,
              BooleanExpressionImpl,
              BooleanType,
              ColumnImpl,
              CompExpressionImpl,
              CompilationUnitImpl,
              ComponentDeclarationImpl,
              ConcatenationExpressionImpl,
              ConstDeclarationImpl,
              ContextDeclarationImpl,
              DataSourceAssociationImpl,
              DataSourceImpl,
              DdlStatementImpl,
              ElementDeclarationImpl,
              EntityDeclarationImpl,
              EnumerationDeclarationImpl,
              EnumerationValueImpl,
              EObjectContainmentEList,
              EObjectImpl,
              ExpressionContainerImpl,
              ExpressionImpl,
              ForeignKeyImpl,
              FuncExpressionImpl,
              GroupByEntryImpl,
              GroupByImpl,
              IAstFactory,
              ImplementedByImpl,
              InExpressionImpl,
              JoinDataSourceImpl,
              JoinEnum,
              LikeExpressionImpl,
              LiteralExpressionImpl,
              NamedDeclarationImpl,
              NamespaceDeclarationImpl,
              NotExpressionImpl,
              NullExpressionImpl,
              OrderByEntryImpl,
              OrderByImpl,
              PathDeclarationImpl,
              PathEntryImpl,
              PathExpressionImpl,
              PreAnnotationImpl,
              ReturnStructureImpl,
              ReturnStructureListImpl,
              ReturnStructureNameImpl,
              SelectListEntryExtensionImpl,
              SelectListEntryImpl,
              SelectListEntryType,
              SelectListImpl,
              SourceRangeImpl,
              StatementContainerImpl,
              StdFuncExpressionImpl,
              TableFunctionImpl,
              TypeDeclarationImpl,
              UsingDirectiveImpl,
              ViewDefinitionImpl,
              ViewExtendImpl,
              ViewSelectImpl,
              SearchedCaseExpressionImpl,
              SimpleCaseExpressionImpl,
              CaseWhenExpressionImpl,
              ArithmeticExpressionImpl,
              PostAnnotationImpl,
              AbstractDdlCodeCompletionProposal,
              AbstractDdlParser,
              AbstractDdlVisitor,
              AnnotationPayload,
              AnnotationUtil,
              DdlCodeCompletionType,
              DdlColumnSelectListEntry,
              DdlCompletionProposal,
              DdlCompletionScope,
              DdlDataSourceAssociationDefinition,
              DdlDataSourceInformation,
              DdlDataSourceParameter,
              DdlErrorneousParserBackendInfo,
              DdlKeywordCodeCompletionProposal,
              DdlParserBackendInfo,
              DdlParserFactoryBackendVersion,
              DdlRndParserApi,
              DdlScanner,
              DdlSourceColoringCacheHelper,
              DdlSourceFormattingStyle,
              DdlStatementMatchUtil,
              DdlTypeUsagePayload,
              PredefinedDataType,
              SapDdlConstants,
              SapViewFormatter,
              TokenUtil,
              WordFormattingEnum,
              SelectImpl,
              ViewSelectSetImpl,
              Region,
              RuleDeclarationImpl,
              AccessPolicyDeclarationImpl,
              RoleDeclarationImpl,
              AspectDeclarationImpl,
              SourceRenderer,
              CardinalityRestrictionImpl,
              RemoveSelectListEntryCommand,
              RemoveParameterCommand,
              RemoveAliasForSelectListEntryCommand,
              RemoveAnnotationCommand,
              AstMerger,
              ReplaceSelectListEntryCommand,
              AddAnnotationCommand,
              ReplaceAnnotationCommand,
              ReplaceSingleTokenLexemCommand,
              AddToListCommand,
              ReplaceParameterCommand,
              MoveAstObjectInListCommand,
              AddAliasForSelectListEntryCommand,
              AddSelectListEntryCommand,
              AddAnnotationForViewDefinitionCommand,
              AddAnnotationForSelectListEntryCommand,
              ModifyAnnotationForSelectListEntryCommand,
              ModifyAnnotationForViewDefinitionCommand,
              ModifyEndUserTextCommand,
              AddParameterCommand,
              MoveSelectListEntryCommand,
              SourceModificationCommandFactory,
              SetWhereClauseCommand,
              ConstructorFuncExpressionImpl,
              ExpressionsContainerExpressionImpl,
              ExtractFunctionExpressionImpl,
              TrimFunctionExpressionImpl,
              AbstractPathEntryImpl,
              NestedFlattenedSelectListPathEntryImpl,
              NestedSelectListPathEntryImpl,
              IncludedRoleImpl,
              AstNodeUtil,
              CodePattern) {

        return {
            AbapMethodImpl: AbapMethodImpl,
            AbstractAnnotationImpl: AbstractAnnotationImpl,
            AbstractAnnotationValueImpl: AbstractAnnotationValueImpl,
            AnnotatedImpl: AnnotatedImpl,
            AnnotationArrayValueImpl: AnnotationArrayValueImpl,
            AnnotationDeclarationImpl: AnnotationDeclarationImpl,
            AnnotationNameValuePairImpl: AnnotationNameValuePairImpl,
            AnnotationPathValueImpl: AnnotationPathValueImpl,
            AnnotationRecordValueImpl: AnnotationRecordValueImpl,
            AnnotationValueImpl: AnnotationValueImpl,
            AnonymousTypeDeclarationImpl: AnonymousTypeDeclarationImpl,
            AssociationDeclarationImpl: AssociationDeclarationImpl,
            AssociationContainerImpl: AssociationContainerImpl,
            AstFactoryImpl: AstFactoryImpl,
            AttributeDeclarationImpl: AttributeDeclarationImpl,
            BetweenExpressionImpl: BetweenExpressionImpl,
            BooleanExpressionImpl: BooleanExpressionImpl,
            BooleanType: BooleanType,
            ColumnImpl: ColumnImpl,
            CompExpressionImpl: CompExpressionImpl,
            CompilationUnitImpl: CompilationUnitImpl,
            ComponentDeclarationImpl: ComponentDeclarationImpl,
            ConcatenationExpressionImpl: ConcatenationExpressionImpl,
            ConstDeclarationImpl: ConstDeclarationImpl,
            ContextDeclarationImpl: ContextDeclarationImpl,
            DataSourceAssociationImpl: DataSourceAssociationImpl,
            DataSourceImpl: DataSourceImpl,
            DdlStatementImpl: DdlStatementImpl,
            ElementDeclarationImpl: ElementDeclarationImpl,
            EntityDeclarationImpl: EntityDeclarationImpl,
            EnumerationDeclarationImpl: EnumerationDeclarationImpl,
            EnumerationValueImpl: EnumerationValueImpl,
            EObjectContainmentEList: EObjectContainmentEList,
            EObjectImpl: EObjectImpl,
            ExpressionContainerImpl: ExpressionContainerImpl,
            ExpressionImpl: ExpressionImpl,
            ForeignKeyImpl: ForeignKeyImpl,
            FuncExpressionImpl: FuncExpressionImpl,
            GroupByEntryImpl: GroupByEntryImpl,
            GroupByImpl: GroupByImpl,
            IAstFactory: IAstFactory,
            ImplementedByImpl: ImplementedByImpl,
            InExpressionImpl: InExpressionImpl,
            JoinDataSourceImpl: JoinDataSourceImpl,
            JoinEnum: JoinEnum,
            LikeExpressionImpl: LikeExpressionImpl,
            LiteralExpressionImpl: LiteralExpressionImpl,
            NamedDeclarationImpl: NamedDeclarationImpl,
            NamespaceDeclarationImpl: NamespaceDeclarationImpl,
            NotExpressionImpl: NotExpressionImpl,
            NullExpressionImpl: NullExpressionImpl,
            OrderByEntryImpl: OrderByEntryImpl,
            OrderByImpl: OrderByImpl,
            PathDeclarationImpl: PathDeclarationImpl,
            PathEntryImpl: PathEntryImpl,
            PathExpressionImpl: PathExpressionImpl,
            PreAnnotationImpl: PreAnnotationImpl,
            ReturnStructureImpl: ReturnStructureImpl,
            ReturnStructureListImpl: ReturnStructureListImpl,
            ReturnStructureNameImpl: ReturnStructureNameImpl,
            SelectListEntryExtensionImpl: SelectListEntryExtensionImpl,
            SelectListEntryImpl: SelectListEntryImpl,
            SelectListEntryType: SelectListEntryType,
            SelectListImpl: SelectListImpl,
            SourceRangeImpl: SourceRangeImpl,
            StatementContainerImpl: StatementContainerImpl,
            StdFuncExpressionImpl: StdFuncExpressionImpl,
            TableFunctionImpl: TableFunctionImpl,
            TypeDeclarationImpl: TypeDeclarationImpl,
            UsingDirectiveImpl: UsingDirectiveImpl,
            ViewDefinitionImpl: ViewDefinitionImpl,
            ViewExtendImpl: ViewExtendImpl,
            ViewSelectImpl: ViewSelectImpl,
            SearchedCaseExpressionImpl: SearchedCaseExpressionImpl,
            SimpleCaseExpressionImpl: SimpleCaseExpressionImpl,
            CaseWhenExpressionImpl: CaseWhenExpressionImpl,
            ArithmeticExpressionImpl: ArithmeticExpressionImpl,
            PostAnnotationImpl: PostAnnotationImpl,
            AbstractDdlCodeCompletionProposal: AbstractDdlCodeCompletionProposal,
            AbstractDdlParser: AbstractDdlParser,
            AbstractDdlVisitor: AbstractDdlVisitor,
            AnnotationPayload: AnnotationPayload,
            AnnotationUtil: AnnotationUtil,
            DdlCodeCompletionType: DdlCodeCompletionType,
            DdlColumnSelectListEntry: DdlColumnSelectListEntry,
            DdlCompletionProposal: DdlCompletionProposal,
            DdlCompletionScope: DdlCompletionScope,
            DdlDataSourceAssociationDefinition: DdlDataSourceAssociationDefinition,
            DdlDataSourceInformation: DdlDataSourceInformation,
            DdlDataSourceParameter: DdlDataSourceParameter,
            DdlErrorneousParserBackendInfo: DdlErrorneousParserBackendInfo,
            DdlKeywordCodeCompletionProposal: DdlKeywordCodeCompletionProposal,
            DdlParserBackendInfo: DdlParserBackendInfo,
            DdlParserFactoryBackendVersion: DdlParserFactoryBackendVersion,
            DdlRndParserApi: DdlRndParserApi,
            DdlScanner: DdlScanner,
            DdlSourceColoringCacheHelper: DdlSourceColoringCacheHelper,
            DdlSourceFormattingStyle: DdlSourceFormattingStyle,
            DdlStatementMatchUtil: DdlStatementMatchUtil,
            DdlTypeUsagePayload: DdlTypeUsagePayload,
            PredefinedDataType: PredefinedDataType,
            SapDdlConstants: SapDdlConstants,
            SapViewFormatter: SapViewFormatter,
            TokenUtil: TokenUtil,
            WordFormattingEnum: WordFormattingEnum,
            SelectImpl: SelectImpl,
            ViewSelectSetImpl: ViewSelectSetImpl,
            Region: Region,
            RuleDeclarationImpl: RuleDeclarationImpl,
            AccessPolicyDeclarationImpl: AccessPolicyDeclarationImpl,
            RoleDeclarationImpl: RoleDeclarationImpl,
            AspectDeclarationImpl: AspectDeclarationImpl,
            SourceRenderer: SourceRenderer,
            CardinalityRestrictionImpl: CardinalityRestrictionImpl,
            RemoveSelectListEntryCommand: RemoveSelectListEntryCommand,
            RemoveParameterCommand: RemoveParameterCommand,
            RemoveAliasForSelectListEntryCommand: RemoveAliasForSelectListEntryCommand,
            RemoveAnnotationCommand: RemoveAnnotationCommand,
            AstMerger: AstMerger,
            ReplaceSelectListEntryCommand: ReplaceSelectListEntryCommand,
            AddAnnotationCommand: AddAnnotationCommand,
            ReplaceAnnotationCommand: ReplaceAnnotationCommand,
            ReplaceSingleTokenLexemCommand: ReplaceSingleTokenLexemCommand,
            AddToListCommand: AddToListCommand,
            ReplaceParameterCommand: ReplaceParameterCommand,
            MoveAstObjectInListCommand: MoveAstObjectInListCommand,
            AddAliasForSelectListEntryCommand: AddAliasForSelectListEntryCommand,
            AddSelectListEntryCommand: AddSelectListEntryCommand,
            AddAnnotationForViewDefinitionCommand: AddAnnotationForViewDefinitionCommand,
            AddAnnotationForSelectListEntryCommand: AddAnnotationForSelectListEntryCommand,
            ModifyAnnotationForSelectListEntryCommand: ModifyAnnotationForSelectListEntryCommand,
            ModifyAnnotationForViewDefinitionCommand: ModifyAnnotationForViewDefinitionCommand,
            ModifyEndUserTextCommand: ModifyEndUserTextCommand,
            AddParameterCommand: AddParameterCommand,
            MoveSelectListEntryCommand: MoveSelectListEntryCommand,
            SourceModificationCommandFactory: SourceModificationCommandFactory,
            SetWhereClauseCommand: SetWhereClauseCommand,
            ConstructorFuncExpressionImpl: ConstructorFuncExpressionImpl,
            ExpressionsContainerExpressionImpl: ExpressionsContainerExpressionImpl,
            ExtractFunctionExpressionImpl: ExtractFunctionExpressionImpl,
            TrimFunctionExpressionImpl: TrimFunctionExpressionImpl,
            AbstractPathEntryImpl: AbstractPathEntryImpl,
            NestedFlattenedSelectListPathEntryImpl: NestedFlattenedSelectListPathEntryImpl,
            NestedSelectListPathEntryImpl: NestedSelectListPathEntryImpl,
            IncludedRoleImpl: IncludedRoleImpl,
            AstNodeUtil: AstNodeUtil,
            CodePattern: CodePattern
        };
    }
);
