window.TEST_REGEXP = /sane-tests\/extensibility\/.*Spec\.js$/i;
window.allTestFiles = [
	'extensibility/AppDescriptor/ExtensibilityWithAppDescriptorSpec',
	'extensibility/AddExtension/ExtendControllerSpec',
	'extensibility/AddExtension/ExtendControllerHookSpec',
	'extensibility/AddExtension/ReplaceViewSpec',
	'extensibility/AddExtension/ReplaceServiceSpec',
	'extensibility/AddExtension/i18nComponentSpec',
	'extensibility/WelcomeScreen/WelcomeScreenSpec',
	'extensibility/WelcomeScreen/VersionSpec',
	'extensibility/WelcomeScreen/WelcomeScreenPersistencySpec',
	'extensibility/ExtensionProject/ExtensionProjectTemplateSpec',
	'extensibility/ExtensionProject/ExtensionProjectServiceSpec',
	'extensibility/ExtensionProject/CreateExtensionProjectSpec',
	'extensibility/ExtensionProject/ParentProjectControllerSpec',
	'extensibility/FLP/FioriLaunchpadSpec',
	'extensibility/FLP/GeneralInfoStepSpec',
	'extensibility/Deployment/DeployWizardSpec',
	'extensibility/Deployment/BSPParentProjectSpec',
	'extensibility/Deployment/HeliumParentProjectSpec',
	'extensibility/Deployment/WorkspaceParentProjectSpec',
	'extensibility/Deployment/ApplicationSyncUtilitySpec',
	'extensibility/Deployment/ABAPRepositorySpec',
	'extensibility/Deployment/TransportSpec',
	'extensibility/Deployment/DiscoverySpec',
	'extensibility/Deployment/SearchSpec',
	'extensibility/Deployment/DeploymentUtilitySpec',
	'extensibility/Deployment/DeploymentSpec',
	'extensibility/Deployment/SelectDeployABAPSystemStepSpec',
	'extensibility/lib/escodegen/escodegenBrowserSpec',
	'extensibility/ExtensibilityPane/ExtendUtilSpec',
	'extensibility/ExtensibilityPane/UIContentSpec',
	'extensibility/ExtensibilityPane/TransceiverSpec',
	'extensibility/ExtensibilityPane/ExtensionProjectTreeSpec',
	'extensibility/unit/WorkspaceApplicationFactorySpec',
	'extensibility/ComponentManager/ComponentManagerSpec',
	'extensibility/util/XmlUtilSpec',
	'extensibility/util/ExtensionProjectSettingsSpec',
	'extensibility/util/ExtensionHookSpec',
	'extensibility/UIAdaptation/UIAdaptationSpec',
	'extensibility/util/HCPConnectivitySpec',
	'extensibility/ExternalCommands/ExtendProjectExternalCommandSpec',
	'extensibility/TipsAndTricks/CyclicDoublyLinkedListSpec',
	'extensibility/TipsAndTricks/TipsAndTricksManagerSpec',
	'extensibility/TipsAndTricks/TipsAndTricksOpenerSpec',
	'extensibility/TipsAndTricks/TipsAndTricksCommandSpec',
	'extensibility/TipsAndTricks/TipsAndTricksViewsFactorySpec'

];

window.customPaths = {
	'extensibility': window.webappPath() + 'test-resources/sap/watt/sane-tests/extensibility',
	'fakeFileDAO': window.webappPath() + 'test-resources/sap/watt/util/fakeFileBackend/FakeFileDAO',
	'sap.watt.common.filesystem': window.webappPath() + 'resources/sap/watt/common/plugin/filesystem',
	'sap.watt.saptoolsets.fiori.abap.adt.communication' : window.webappPath() + 'resources/sap/watt/saptoolsets/fiori/abap/plugin/adt/communication',
	'sap.watt.saptoolsets.fiori.abap.adt.compatibility' : window.webappPath() + 'resources/sap/watt/saptoolsets/fiori/abap/plugin/adt/compatibility',
	'sinon': window.webappPath() + 'test-resources/sap/watt/sane-tests/libs/sinon-1.15.0'
};