define(function() {
	return {
    	 CREATE_ACTION : 1,
    	 UPDATE_ACTION : 2,
    	 DELETE_ACTION : 3,
    	 TRANSPORT_STATUS_S : 4,
    	 TRANSPORT_STATUS_E : 5,
    	 TRANSPORT_STATUS_LOCKED : 6,
    	 TRANSPORT_STATUS_NOT_ASSAIGNED : 7,
    	 TRANSPORT_STATUS_LOCAL_PACKAGE : 8
	};
});