/*Copyright © 2015 SAP SE or an affiliate company. All rights reserved.*/
jQuery.sap.declare("sap.watt.hanaplugins.editor.plugin.hdbcalculationview.view.mapping.Images");
sap.watt.hanaplugins.editor.plugin.hdbcalculationview.view.mapping.Images = {
    "ATTRIBUTE": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/Attribute.png",
    "ATTRIBUTE_ERROR": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/proxy/Attribute.png",
	"ATTRIBUTE_DELETE": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/proxy/DepreAttribute.png",
    "MEASURE": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/Measure.png",
    "MEASURE_ERROR": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/proxy/Measure.png",
 	"MEASURE_DELETE": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/proxy/DepreMeasure.png",
    "CUBE": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/cube.png",
    "DATA_BASE_TABLE": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/Table.png",
    "DATA_BASE_TABLE_PROXY": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/proxy/Table.png",
    "COLUMN": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/Column.png",
    "COLUMN_ERROR": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/proxy/Column.png",
    "COLUMN_PROXY": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/proxy/ColumnProxy.png",
    "VIEW": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/view.jpg",
    "ADD": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/Add.png",
    "TRASH": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/Trash.gif",
    "AUTOMAP": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/Automap.png",
    "PROJECTION": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/Projection.png",
    "AGGREGATION": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/Aggregation.png",
    "RANK": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/Rank.png",
    "JOINNODE": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/Join.png",
    "UNION": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/Union.png",
    "PARAMETER": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/Parameter.png",
    "VARIABLE": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/variable.png",
    "CONSTANT": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/Constant.png",
    "CALCULATIONVIEW": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/calculation_scenario.png",
    "ATTRIBUTEVIEW": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/AttributeView.png",
    "ANALYTICVIEW": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/AnalyticView.png",
    "PROCEDURE": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/procedure.gif",
    "HDBPROCEDURE": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/HDBProcedure.gif",
    "HDBTABLEFUNCTION": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/TableFunction.gif",
    "HDBTABLEFUNCTION_ERROR": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/TableFunctionError.gif",

    "CALCULATIONVIEW_PROXY": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/proxy/calculation_scenario.png",
    "ATTRIBUTEVIEW_PROXY": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/proxy/AttributeView.png",
    "ANALYTICVIEW_PROXY": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/proxy/AnalyticView.png",
    "PARAMETER_PROXY": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/proxy/Parameter.png",
    "PARAMETER_ERROR": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/proxy/ParameterProxy.png",
    "VARIABLE_PROXY": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/proxy/variable.png",
    "PROCEDURE_PROXY": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/proxy/procedure.gif",
    "HDBPROCEDURE_PROXY": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/proxy/HDBProcedure.gif",
    "HDBTABLEFUNCTION_PROXY": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/proxy/TableFunction.gif",

    "CALCULATIONVIEW_HISTORY": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/CalculationView_History.png",
    "PARAMETER_HISTORY": "/watt/resources/sap/watt/hanaplugins/editor/plugin/hdbcalculationview/images/Parameter_History.png"

};
